#server:
#  port: 8091
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee_db
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  application:
    name: EMPLOYEE-SERVICE   #this name shld be same as in the config server file name (irrespective of the case)
  config:
    import: optional:configserver:http://localhost:8888
#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/


#Actuator endpoints for circuit breaker
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


#CircuitBreaker endpoints
resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      EMPLOYEE-SERVICE:
        max-attempts: 5
        waitDuration: 5s


